# Generated by Django 5.0.3 on 2024-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudOnSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.PositiveIntegerField(default=False)),
                ('latency', models.PositiveIntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StorageServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disks2_5', models.PositiveIntegerField(default=False)),
                ('disks3_5', models.PositiveIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('processors', models.PositiveIntegerField(max_length=3)),
                ('raid5', models.BooleanField(default=False)),
                ('raid6', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StorageProc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cores', models.PositiveIntegerField(default=False)),
                ('threads', models.PositiveIntegerField(default=False)),
                ('cache', models.PositiveIntegerField(default=False)),
                ('compatible_ram', models.CharField(default=False, max_length=100)),
                ('server_id', models.ManyToManyField(to='CloudOnSite.storageserver')),
            ],
        ),
    ]
